START TRANSACTION;
CREATE TABLE Marc(
  ID SERIAL PRIMARY KEY,
  Marc VARCHAR(255) NOT NULL 
);

CREATE TABLE Model_car(
    ID SERIAL PRIMARY KEY,
    Model VARCHAR(255) NOT NULL
);

CREATE TABLE Body(
  ID SERIAL PRIMARY KEY ,
  Name_body VARCHAR(255) NOT NULL
);

CREATE TABLE Characteristic(
    ID SERIAL PRIMARY KEY,
    ID_marc INTEGER REFERENCES Marc(ID) ON DELETE SET NULL ON UPDATE CASCADE,
    ID_model INTEGER REFERENCES Model_car(ID) ON DELETE SET NULL ON UPDATE CASCADE,
    ID_body INTEGER REFERENCES Body(ID) ON DELETE SET NULL ON UPDATE CASCADE,
    Year_issue INTEGER NOT NULL,
    Color VARCHAR (255),
    Volume FLOAT NOT NULL,
    Price INTEGER NOT NULL
);

COMMIT;